behaviors:
  SumoBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 0.01
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
        learning_rate: 3.0e-4
        use_actions: true
        use_vail: false
        demo_path: Rita_Pokaimon_Playground/Assets/Demonstrations/SumoBall_Model_49997/
    keep_checkpoints: 5
    max_steps: 5000000
    # init_path: results/gail_prep_many_ckpt/SumoBall/SumoBall-49997.pt
    time_horizon: 64
    summary_freq: 10000
    # behavioral_cloning:
    #   demo_path: Rita_Pokaimon_Playground/Assets/Demonstrations/SumoBall_Model_49997/
    #   steps: 50000
    #   strength: 0.1
    #   samples_per_update: 0
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 50000
      swap_steps: 2000
      team_change: 100000
      initial_elo: 1392

    